apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  project: default
  source:
    chart: bitnami/cert-manager
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 0.1.21
    helm:
      releaseName: cert-manager
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager

