apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app
  namespace: ingress-nginx
spec:
  project: default
  source:
    chart: nginx-ingress-controller
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 8.0.7

    helm:
      values: |
        
        watchIngressWithoutClass: false
        
        ingressClass: nginx

        # This argument is required for the controller to register the 'nginx' ingress class (workaround for what might be a bug)
        extraArgs:
          ingress-class-by-name: true

        replicaCount: 1

        defaultBackend:
          enabled: true
          replicaCount: 1

        service:
          type: LoadBalancer
          externalTrafficPolicy: Local # enables client IP passthrough in 'X-Forwarder-For' header

        serviceAccount:
          create: true

        rbac:
          create: true

        metrics:
          enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true



